name: Tests

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    services:
      postgres:
        image: postgres:11.10
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432/tcp
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9.5"
      - run: pip install poetry
      - name: Set Poetry config
        run: poetry config virtualenvs.path ~/.virtualenvs
      - name: Cache Poetry
        uses: actions/cache@v1
        id: cache
        with:
          path: ~/.virtualenvs
          key: poetry-toolkit-${{ hashFiles('**/poetry.lock') }}-v2
      - name: Install deps
        run: poetry install
      - name: Unit tests
        run: poetry run task test
        env:
          DATABASE_URL: postgresql+asyncpg://postgres:postgres@localhost:${{ job.services.postgres.ports[5432] }}/postgres
          IDENTITY_SECRET: 'secret'
          PASTAPORTO_SECRET: 'secret'
          SERVICE_TO_SERVICE_SECRET: 'secret'
          PASTAPORTO_ACTION_SECRET: 'secret'
